/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package smpis_system;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vandens
 */
public class admin_add_form extends javax.swing.JDialog {

    public Connection dbconnect = dbconnection.getConnection();
    public String error_msg;
    public String sql;
    /**
     * Creates new form student_add_form
     * @param flag
     */
    public admin_add_form(String flag) {
        initComponents();
        setModal(true);
        if(flag.equals("Add")){
            update.setEnabled(false);
            save.setEnabled(true);
        }else{
            update.setEnabled(true);
            save.setEnabled(false);
            param1.setEnabled(false);
            this.edit(flag);
        }
        System.out.println(flag);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        param1 = new javax.swing.JTextField();
        param2 = new javax.swing.JTextField();
        param3 = new javax.swing.JTextField();
        param5 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        param7 = new javax.swing.JTextArea();
        date_param1 = new javax.swing.JComboBox();
        date_param2 = new javax.swing.JComboBox();
        date_param3 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        param4 = new javax.swing.JComboBox();
        param6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        param8 = new javax.swing.JPasswordField();
        update = new javax.swing.JButton();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setTitle("Form Data Admin");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Data Pribadi"));

        jLabel8.setText("ID Admin");

        jLabel9.setText("Nama Lengkap Admin");

        jLabel10.setText("Tempat, Tanggal Lahir");

        jLabel11.setText("Agama");

        param1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                param1ActionPerformed(evt);
            }
        });

        param5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih satu", "Islam", "Katolik", "Protestan", "Hindu", "Budha", "Kong Hu Cu" }));
        param5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                param5ActionPerformed(evt);
            }
        });

        jLabel4.setText("Alamat");

        param7.setColumns(20);
        param7.setRows(5);
        jScrollPane1.setViewportView(param7);

        date_param1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tgl", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        date_param1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_param1ActionPerformed(evt);
            }
        });

        date_param2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bulan", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        date_param2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_param2ActionPerformed(evt);
            }
        });

        date_param3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tahun", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016" }));
        date_param3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_param3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Jenis Kelamin");

        param4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih satu", "Laki-laki", "Perempuan" }));

        param6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                param6ActionPerformed(evt);
            }
        });

        jLabel12.setText("No Telp ");

        jLabel16.setText("Kata Sandi");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(param4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(param5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(param3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date_param1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date_param2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date_param3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16))
                        .addGap(139, 139, 139)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(param6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(param1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(param2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(param8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(param1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(param2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(param8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(param3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_param1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_param2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_param3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(param4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(param5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(param6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24))
        );

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/update.png"))); // NOI18N
        update.setText("Update");
        update.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/save_as.png"))); // NOI18N
        save.setText("Simpan");
        save.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/cancel.png"))); // NOI18N
        cancel.setText("Batal");
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Sistem Informasi Pembayaran Sekolah");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("SMA Negeri 6 Kab. Tangerang");

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel14.setText("Jalan Aria Jaya Sentika No. 52 Pasirnangka, Tigaraksa - Tangerang, 15720 - (021) 5990276");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smpis_system/logo-in.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update)
                    .addComponent(save)
                    .addComponent(cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void param1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_param1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_param1ActionPerformed

    private void param5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_param5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_param5ActionPerformed

    private void date_param1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_param1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_param1ActionPerformed

    private void date_param2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_param2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_param2ActionPerformed

    private void date_param3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_param3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_param3ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        admin_update();
        this.dispose();
        revalidate();
    }//GEN-LAST:event_updateActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        admin_save();
        revalidate();
        clear_text();
    }//GEN-LAST:event_saveActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void param6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_param6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_param6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox date_param1;
    private javax.swing.JComboBox date_param2;
    private javax.swing.JComboBox date_param3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField param1;
    private javax.swing.JTextField param2;
    private javax.swing.JTextField param3;
    private javax.swing.JComboBox param4;
    private javax.swing.JComboBox param5;
    private javax.swing.JTextField param6;
    private javax.swing.JTextArea param7;
    private javax.swing.JPasswordField param8;
    private javax.swing.JButton save;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables


    public void clear_text(){
        param1.setText("");
        param2.setText("");
        param3.setText("");
        date_param1.setSelectedItem("Tgl");
        date_param2.setSelectedItem("Bulan");
        date_param3.setSelectedItem("Tahun");
        param4.setSelectedItem("Pilih satu");
        param5.setSelectedItem("Pilih satu");
        param6.setText("");
        param7.setText("");
        param8.setText("");
    }
    
    public void admin_save(){
        
        String admin_id       = param1.getText();
        String admin_fullname = param2.getText();
        String admin_bplace   = param3.getText();
        String admin_religion = (String) param5.getSelectedItem();
        String ad_sex      = (String) param4.getSelectedItem();
        String date           = (String) date_param1.getSelectedItem();
        String month          = (String) date_param2.getSelectedItem();
        String year           = (String) date_param3.getSelectedItem();
        String admin_phone    = param6.getText();
        String admin_address  = param7.getText();
        String admin_pass     = param8.getText();
        
        
        // ------------------ validasi data dulu disini  -----------------
        if("".equals(admin_id))                                              error_msg = "ID tidak boleh kosong";
        if("".equals(admin_pass))                                              error_msg = "Password tidak boleh kosong";
        else if("".equals(admin_fullname))                                        error_msg = "Nama lengkap tidak boleh kosong";
        else if("".equals(admin_bplace))                                          error_msg = "Tempat lahir tidak boleh kosong";
        else if("".equals(date) || date.equals("Tgl"))                              error_msg = "Tanggal lahir tidak boleh kosong";
        else if("".equals(ad_sex))                                                  error_msg = "Jenis kelamin tidak boleh kosong";
        else if("".equals(month) || month.equals("Bulan"))                          error_msg = "Bulan lahir tidak boleh kosong";
        else if("".equals(year) || year.equals("Tahun"))                            error_msg = "Tahun lahir tidak boleh kosong";
        // ------------------ tambah validasi lainnya disini -----------------        
        else error_msg = "";
        
        
        if(error_msg.equals("")){
            try {                  
                    String admin_bday = year+"-"+month+"-"+date;
                    String admin_sex  = ("Laki-laki".equals(ad_sex)) ? "L" : "P";
                    Statement stmt = dbconnect.createStatement();
                    sql = "INSERT INTO m_admin"
                                    + "(admin_id, admin_password, admin_fullname, admin_sex, admin_bplace, admin_bday, admin_religion, admin_phone, admin_address)"
                                    + " VALUE"
                                    + "('"+admin_id+"','"+admin_pass+"', '"+admin_fullname+"','"+admin_sex+"','"+admin_bplace+"','"+admin_bday+"','"+admin_religion+"','"+admin_phone+"','"+admin_address+"')";
                    System.out.println(sql);
                    stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(rootPane,"Data berhasil disimpan!","Simpan",JOptionPane.INFORMATION_MESSAGE);
                        
            } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane,"Error : "+ex,"Error",JOptionPane.ERROR);
            }
            
        }else JOptionPane.showMessageDialog(rootPane,error_msg,"Error",JOptionPane.ERROR_MESSAGE);
        
    }
    
    private void edit(String key) {
       try{
           Statement stmt           = dbconnect.createStatement();
           sql                      = "SELECT admin_id, admin_password, admin_fullname, admin_sex, admin_bplace, admin_bday, admin_religion, admin_phone, admin_address"
                                    + " FROM m_admin WHERE admin_id = '"+key+"'";
           ResultSet rs   = stmt.executeQuery(sql);
           
           while(rs.next()){
               param1.setText(rs.getString("admin_id"));
               param2.setText(rs.getString("admin_fullname"));
               param3.setText(rs.getString("admin_bplace"));
               param5.setSelectedItem(rs.getString("admin_religion"));
               param7.setText(rs.getString("admin_address"));
               String st_sex = ("L".equals(rs.getString("admin_sex"))) ? "Laki-laki" : "Perempuan";
               param4.setSelectedItem(st_sex);  
               param6.setText(rs.getString("admin_phone")); 
               param8.setText(rs.getString("admin_password"));          
              
               String[] split = rs.getString("admin_bday").split("-");
               
               date_param1.setSelectedItem(split[2]);
               date_param2.setSelectedItem(split[1]);
               date_param3.setSelectedItem(split[0]);
           }
           
       }catch(SQLException e){
           JOptionPane.showMessageDialog(rootPane,"Error : "+e,"Error",JOptionPane.ERROR);
       }
       
    }

    private void admin_update() {
       
        String admin_id       = param1.getText();
        String admin_fullname = param2.getText();
        String admin_bplace   = param3.getText();
        String admin_religion = (String) param5.getSelectedItem();
        String ad_sex      = (String) param4.getSelectedItem();
        String date           = (String) date_param1.getSelectedItem();
        String month          = (String) date_param2.getSelectedItem();
        String year           = (String) date_param3.getSelectedItem();
        String admin_phone    = param6.getText();
        String admin_address  = param7.getText();
        String admin_pass     = param8.getText();
        
        
        // ------------------ validasi data dulu disini  -----------------
        if("".equals(admin_id))                                              error_msg = "ID tidak boleh kosong";
        if("".equals(admin_pass))                                              error_msg = "Password tidak boleh kosong";
        else if("".equals(admin_fullname))                                        error_msg = "Nama lengkap tidak boleh kosong";
        else if("".equals(admin_bplace))                                          error_msg = "Tempat lahir tidak boleh kosong";
        else if("".equals(date) || date.equals("Tgl"))                              error_msg = "Tanggal lahir tidak boleh kosong";
        else if("".equals(ad_sex))                                                  error_msg = "Jenis kelamin tidak boleh kosong";
        else if("".equals(month) || month.equals("Bulan"))                          error_msg = "Bulan lahir tidak boleh kosong";
        else if("".equals(year) || year.equals("Tahun"))                            error_msg = "Tahun lahir tidak boleh kosong";
        // ------------------ tambah validasi lainnya disini -----------------        
        else error_msg = "";
        
        
        if(error_msg.equals("")){
            try {                  
                    String admin_bday = year+"-"+month+"-"+date;
                    String admin_sex  = ("Laki-laki".equals(ad_sex)) ? "L" : "P";
                    Statement stmt = dbconnect.createStatement();
                    sql = "UPDATE m_admin SET "
                                    + "admin_fullname = '"+admin_fullname+"', admin_password = '"+admin_pass+"', "
                                    + "admin_sex = '"+admin_sex+"', admin_bplace = '"+admin_bplace+"', admin_bday = '"+admin_bday+"', admin_religion = '"+admin_religion+"',"
                                    + " admin_phone = '"+admin_phone+"',"
                                    + " admin_address = '"+admin_address+"' WHERE admin_id = '"+admin_id+"'";
                    System.out.println(sql);
                    stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(rootPane,"Data berhasil disimpan!","Berhasil",JOptionPane.INFORMATION_MESSAGE);
                        
            } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane,"Error : "+ex,"Error",JOptionPane.ERROR);
            }
            
        }else JOptionPane.showMessageDialog(rootPane,error_msg,"Error",JOptionPane.ERROR_MESSAGE);
        
    }
}
