/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package smpis_system;

import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author vandens
 */
public class student_list extends javax.swing.JPanel {

    public Connection dbconnect = dbconnection.getConnection();
    public DefaultTableModel table_list;
    public String sql;
    private String where = "";
    public String key;
    public Map<String, Object> params;
    /**
     * Creates new form student_list
     */
    public student_list() {
        initComponents();
        show_list(where);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        add_new = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        table_list_student = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        param1 = new javax.swing.JTextField();
        param2 = new javax.swing.JTextField();
        param3 = new javax.swing.JTextField();
        param4 = new javax.swing.JCheckBox();
        param5 = new javax.swing.JCheckBox();
        param6 = new javax.swing.JComboBox();
        clear = new javax.swing.JButton();
        filter = new javax.swing.JButton();

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        add_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/pencil_add.png"))); // NOI18N
        add_new.setText("Tambah");
        add_new.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_newActionPerformed(evt);
            }
        });
        jToolBar1.add(add_new);

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/pencil_go.png"))); // NOI18N
        edit.setText("Edit");
        edit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jToolBar1.add(edit);

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/pencil_delete.png"))); // NOI18N
        delete.setText("Hapus");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jToolBar1.add(delete);

        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/printer.png"))); // NOI18N
        print.setText("Print");
        print.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jToolBar1.add(print);

        table_list_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIS", "Nama Lengkap Siswa", "Kelas", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "Alamat", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scroll.setViewportView(table_list_student);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Filter Data Siswa"));

        jLabel6.setText("NIS");

        jLabel7.setText("Nama Siswa");

        jLabel8.setText("Kelas");

        jLabel9.setText("Jenis Kelamin");

        jLabel10.setText("Status");

        param4.setText("Laki - Laki");

        param5.setText("Perempuan");

        param6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih satu", "Suspended", "Aktif", "Lulus", "Deleted" }));
        param6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                param6ActionPerformed(evt);
            }
        });

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/filter_delete.png"))); // NOI18N
        clear.setText("Clear");
        clear.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        filter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/filter_add.png"))); // NOI18N
        filter.setText("Filter");
        filter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(59, 59, 59))))
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(param4)
                        .addGap(18, 18, 18)
                        .addComponent(param5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(param2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(param1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(param3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(param6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(365, Short.MAX_VALUE)
                .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(param1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(param2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(param3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(param4)
                    .addComponent(param5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(param6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filter)
                    .addComponent(clear))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(scroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_newActionPerformed
        // TODO add your handling code here:
        String flag = "Add";
        student_add_form form = new student_add_form(flag);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_add_newActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:

        boolean is_selected = table_list_student.getSelectedRowCount() > 0;
        if(!is_selected)
        JOptionPane.showMessageDialog(null,"Tidak ada baris terseleksi!","Error",JOptionPane.ERROR_MESSAGE);
        else{
            try{
                key = (String) table_list_student.getValueAt(table_list_student.getSelectedRow(),0);

                student_add_form form = new student_add_form(key);
                form.setLocationRelativeTo(null);
                form.setVisible(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Exception : "+e,"Exception",JOptionPane.ERROR);
            }
        }

    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:

        boolean is_selected = table_list_student.getSelectedRowCount() > 0;
        if(!is_selected)
        JOptionPane.showMessageDialog(null,"Tidak ada baris terseleksi!","Error",JOptionPane.ERROR_MESSAGE);
        else{

            try{

                key = (String) table_list_student.getValueAt(table_list_student.getSelectedRow(),0);
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(this, "Semua data tunggakan dan transaksi akan ikut terhapus.\n Anda yakin ingin melanjutkan?", "Konfirmasi", dialogButton);
                if(dialogResult == 0) {
                    try {
                        if(1!=1){
                            // tambahkan validasi lainnya disini
                            JOptionPane.showMessageDialog(null,"Add Validation Here");
                        }else{

                            Statement stmt = dbconnect.createStatement();
                            // tidak benar-benar dihapus, hanya status saja
                            sql             = "UPDATE m_student SET student_status = 'Deleted', student_updateby = '"+mainform.user_id+"', student_updatetime = NOW() WHERE student_id = '"+key+"'";
                            String sql2     = "UPDATE m_debt SET debt_status = 'Deleted', debt_updateby = '"+mainform.user_id+"', debt_updatetime = NOW() WHERE student_id = '"+key+"'";
                            String sql3     = "UPDATE t_payment SET payment_status = 'Deleted', payment_updateby = '"+mainform.user_id+"', payment_updatetime = NOW() WHERE student_id = '"+key+"'";
                            stmt.executeUpdate(sql);
                            stmt.executeUpdate(sql2);
                            stmt.executeUpdate(sql3);
                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null,"Error : "+e,"Error",JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    System.out.println("No Option");
                }
                show_list(where);

            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Exception : "+e,"Exception",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        try
        {

            String id                   = param1.getText();
            String name                 = param2.getText();
            String clas                 = param3.getText();
            String sex_l                = param4.getText();
            String sex_p                = param5.getText();
            String status               = (String) param6.getSelectedItem();

            boolean L_isSelected = param4.isSelected();
            boolean P_isSelected = param5.isSelected();

            where = "WHERE 1=1 ";
            if(!id.equals(""))                                      where = where+" AND student_id          = '"+id+"'";
            if(!name.equals(""))                                    where = where+" AND student_fullname    LIKE '%"+name+"%'";
            if(!clas.equals(""))                                    where = where+" AND class_name          = '"+clas+"'";
            if(L_isSelected && !P_isSelected)                       where = where+" AND student_sex         = 'L'";
            if(P_isSelected && !L_isSelected)                       where = where+" AND student_sex         = 'P'";
            if(!status.equals("") && !status.equals("Pilih satu"))  where = where+" AND student_status      = '"+status+"'";

            String Query     = "SELECT CONCAT(student_bplace,', ',DATE_FORMAT(student_bday,'%d %b %Y')) as student_bplace, a.*  FROM m_student a "+where;
            System.out.println(Query);
            Map params=new HashMap();
            params.put("QueryString",Query);

            JasperReport jasperReport = JasperCompileManager.compileReport(new File("").getAbsolutePath()+"\\src\\laporan\\student_report_list.jrxml"); //new File("").getAbsolutePath()+"src/com/ztscorp/lms/reports/HibernateQueryDemoReport.jrxml");
        JasperPrint jasperPrint =
        JasperFillManager.fillReport(
            jasperReport, params, dbconnect);

        //JasperExportManager.exportReportToHtmlFile(
            //    jasperPrint, new File("").getAbsolutePath()+"\\src\\laporan\\student_report_list_htm"+".html");

        JasperViewer.viewReport(jasperPrint, false);

        }
        catch (JRException e)
        {
            JOptionPane.showMessageDialog(null,"Exception : "+e,"Exception",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_printActionPerformed

    private void param6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_param6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_param6ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        param1.setText("");
        param2.setText("");
        param3.setText("");
        param4.setSelected(false);
        param5.setSelected(false);
        param6.setSelectedItem("Pilih satu");
        where = "WHERE 1=1 ";
        show_list(where);
    }//GEN-LAST:event_clearActionPerformed

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        // TODO add your handling code here:

        String id                   = param1.getText();
        String name                 = param2.getText();
        String clas                 = param3.getText();
        String sex_l                = param4.getText();
        String sex_p                = param5.getText();
        String status               = (String) param6.getSelectedItem();

        boolean L_isSelected = param4.isSelected();
        boolean P_isSelected = param5.isSelected();

        where = "WHERE 1=1 ";
        if(!id.equals(""))                                      where = where+" AND student_id          = '"+id+"'";
        if(!name.equals(""))                                    where = where+" AND student_fullname    LIKE '%"+name+"%'";
        if(!clas.equals(""))                                    where = where+" AND class_name          = '"+clas+"'";
        if(L_isSelected && !P_isSelected)                       where = where+" AND student_sex         = 'L'";
        if(P_isSelected && !L_isSelected)                       where = where+" AND student_sex         = 'P'";
        if(!status.equals("") && !status.equals("Pilih satu"))  where = where+" AND student_status      = '"+status+"'";

        show_list(where);
    }//GEN-LAST:event_filterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_new;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton filter;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField param1;
    private javax.swing.JTextField param2;
    private javax.swing.JTextField param3;
    private javax.swing.JCheckBox param4;
    private javax.swing.JCheckBox param5;
    private javax.swing.JComboBox param6;
    private javax.swing.JButton print;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable table_list_student;
    // End of variables declaration//GEN-END:variables

    private void show_list(String str_where) {
       
        Object [] rows={"NIS","Nama Lengkap ","Kelas","Tempat Lahir","Tanggal Lahir","Jenis Kelamin","Alamat","Status"};
            table_list=new DefaultTableModel(null,rows);
            table_list_student.setModel(table_list);
            table_list_student.setBorder(null);
            scroll.setVisible(true);
            scroll.setViewportView(table_list_student);
            try{
                
                //String sql="select * from m_student";
                 if(!str_where.equals("")){
                     sql  = "SELECT * FROM m_student "+str_where;
                 }else{
                     sql  = "SELECT * FROM m_student";
                 }
                 
                Statement st = dbconnect.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                String    student_id          = rs.getString("student_id");
                String    student_fullname    = rs.getString("student_fullname");
                String    class_name          = rs.getString("class_name");
                String    student_bplace      = rs.getString("student_bplace");
                String    student_bday        = rs.getString("student_bday");
                String    student_sex         = rs.getString("student_sex");
                String    student_address     = rs.getString("student_address");
                String    student_status      = rs.getString("student_status");

                    String [] tampil={student_id,student_fullname,class_name,student_bplace,student_bday,student_sex,student_address,student_status};
                    table_list.addRow(tampil);
                }
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Terdapat kesalahan query : "+e);
            }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
