/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package smpis_sistem;

import java.awt.Component;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vandens
 */
public class debt_add_form extends javax.swing.JDialog {
    
    public Connection dbconnect = dbconnection.getConnection();
    public DefaultTableModel table_list;
    private DefaultTableModel table_list2;
    public String sql;
    private String where = "";
    public String key;
    private String error_msg = "";
    static final String AB = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
    static SecureRandom rnd = new SecureRandom();
    
    /**
     * Creates new form sample_add_form
     */
    public debt_add_form() {
        initComponents();
        save.setEnabled(false);
        setModal(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_akademis = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        param1 = new javax.swing.JComboBox();
        param2 = new javax.swing.JComboBox();
        panel_tunggakan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        param3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_list_student = new javax.swing.JTable();
        semester2 = new javax.swing.JPanel();
        bulan1 = new javax.swing.JCheckBox();
        bulan2 = new javax.swing.JCheckBox();
        bulan4 = new javax.swing.JCheckBox();
        bulan3 = new javax.swing.JCheckBox();
        bulan5 = new javax.swing.JCheckBox();
        bulan6 = new javax.swing.JCheckBox();
        semester1 = new javax.swing.JPanel();
        bulan7 = new javax.swing.JCheckBox();
        bulan8 = new javax.swing.JCheckBox();
        bulan10 = new javax.swing.JCheckBox();
        bulan9 = new javax.swing.JCheckBox();
        bulan11 = new javax.swing.JCheckBox();
        bulan12 = new javax.swing.JCheckBox();
        process = new javax.swing.JButton();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Data Tunggakan");

        panel_akademis.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Data Akademis"));

        jLabel3.setText("Tahun Ajaran");

        jLabel5.setText("Kelas");

        param1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih satu", "2012/2013", "2013/2014", "2014/2015", "2015/2016", "2016/2017", "2017/2018", "2018/2019", "2019/2020" }));
        param1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                param1ActionPerformed(evt);
            }
        });

        param2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih satu", "10", "11", "12" }));
        param2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                param2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_akademisLayout = new javax.swing.GroupLayout(panel_akademis);
        panel_akademis.setLayout(panel_akademisLayout);
        panel_akademisLayout.setHorizontalGroup(
            panel_akademisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_akademisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_akademisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(116, 116, 116)
                .addGroup(panel_akademisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(param1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(param2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_akademisLayout.setVerticalGroup(
            panel_akademisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_akademisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_akademisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(param1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_akademisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(param2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panel_tunggakan.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Data Tunggakan"));

        jLabel4.setText("Data Bulan diWajibkan");

        jLabel6.setText("Besar Tunggakan (Rp)");

        table_list_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Tunggakan", "Subjek", "Tahun Ajaran", "NIS", "Nama Siswa", "Kelas", "Besar Tunggakan", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_list_student);
        if (table_list_student.getColumnModel().getColumnCount() > 0) {
            table_list_student.getColumnModel().getColumn(0).setHeaderValue("Kode Tunggakan");
            table_list_student.getColumnModel().getColumn(1).setHeaderValue("Subjek");
            table_list_student.getColumnModel().getColumn(2).setHeaderValue("Tahun Ajaran");
            table_list_student.getColumnModel().getColumn(3).setHeaderValue("NIS");
            table_list_student.getColumnModel().getColumn(4).setHeaderValue("Nama Siswa");
            table_list_student.getColumnModel().getColumn(5).setHeaderValue("Kelas");
            table_list_student.getColumnModel().getColumn(6).setHeaderValue("Besar Tunggakan");
            table_list_student.getColumnModel().getColumn(7).setHeaderValue("Status");
        }

        semester2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Semester 2"));

        bulan1.setText("Januari");

        bulan2.setText("Februari");

        bulan4.setText("April");

        bulan3.setText("Maret");

        bulan5.setText("Mei");

        bulan6.setText("Juni");

        javax.swing.GroupLayout semester2Layout = new javax.swing.GroupLayout(semester2);
        semester2.setLayout(semester2Layout);
        semester2Layout.setHorizontalGroup(
            semester2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semester2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(semester2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bulan1)
                    .addComponent(bulan2))
                .addGap(18, 18, 18)
                .addGroup(semester2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bulan3)
                    .addComponent(bulan4))
                .addGap(18, 18, 18)
                .addGroup(semester2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bulan6)
                    .addComponent(bulan5))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        semester2Layout.setVerticalGroup(
            semester2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semester2Layout.createSequentialGroup()
                .addGroup(semester2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bulan1)
                    .addComponent(bulan3)
                    .addComponent(bulan5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(semester2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bulan2)
                    .addComponent(bulan4)
                    .addComponent(bulan6)))
        );

        semester1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Semester 1"));

        bulan7.setText("Juli");

        bulan8.setText("Agustus");

        bulan10.setText("Oktober");

        bulan9.setText("September");

        bulan11.setText("November");

        bulan12.setText("Desember");

        javax.swing.GroupLayout semester1Layout = new javax.swing.GroupLayout(semester1);
        semester1.setLayout(semester1Layout);
        semester1Layout.setHorizontalGroup(
            semester1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semester1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(semester1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bulan7)
                    .addComponent(bulan8))
                .addGap(18, 18, 18)
                .addGroup(semester1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bulan9)
                    .addComponent(bulan10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(semester1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bulan12)
                    .addComponent(bulan11))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        semester1Layout.setVerticalGroup(
            semester1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semester1Layout.createSequentialGroup()
                .addGroup(semester1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bulan9)
                    .addComponent(bulan11)
                    .addComponent(bulan7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(semester1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bulan10)
                    .addComponent(bulan12)
                    .addComponent(bulan8))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_tunggakanLayout = new javax.swing.GroupLayout(panel_tunggakan);
        panel_tunggakan.setLayout(panel_tunggakanLayout);
        panel_tunggakanLayout.setHorizontalGroup(
            panel_tunggakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE)
            .addGroup(panel_tunggakanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_tunggakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGap(67, 67, 67)
                .addGroup(panel_tunggakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(param3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_tunggakanLayout.createSequentialGroup()
                        .addComponent(semester1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(semester2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_tunggakanLayout.setVerticalGroup(
            panel_tunggakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tunggakanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_tunggakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_tunggakanLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_tunggakanLayout.createSequentialGroup()
                        .addComponent(param3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(panel_tunggakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(semester1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(semester2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        process.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/update.png"))); // NOI18N
        process.setText("Proses");
        process.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processActionPerformed(evt);
            }
        });

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/save_as.png"))); // NOI18N
        save.setText("Simpan");
        save.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/cancel.png"))); // NOI18N
        cancel.setText("Batal");
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Sistem Informasi Pembayaran Sekolah");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("SMK Negeri XYZ");

        jLabel24.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel24.setText("Jl. Veteran Raya No 131 - Tigaraksa, Tangerang. Telp 021 599 0217 ");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smpis_sistem/logo - Copy.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addContainerGap(528, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_tunggakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_akademis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(process)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel)))
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_akademis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_tunggakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(process)
                    .addComponent(save)
                    .addComponent(cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void param1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_param1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_param1ActionPerformed

    private void processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processActionPerformed
        // TODO add your handling code here:

        String years            = (String) param1.getSelectedItem();
        String class_name       = (String) param2.getSelectedItem();
        String param3x           = param3.getText();
       
       
        // ------------------ validasi data dulu disini  -----------------
        if(years.equals("Pilih satu"))                      error_msg = "Tahun penerimaan tidak boleh kosong";
        else if(class_name.equals("Pilih satu"))            error_msg = "Kelas tidak boleh kosong";
        else if(param3x.equals("") || param3x.equals("0"))  error_msg = "Besar tunggakan tidak boleh kosong";
        // ------------------ tambah validasi lainnya disini -----------------
        if(error_msg.equals("")){
            
            //jika diperlukan ccy dengan field decimal
            //BigDecimal amount   = new BigDecimal(param3x);
            
            JTable table_list_student2 = new JTable();
            Object [] rows={"Kode Tunggakan","Subjek ","NIS","Nama Siswa","Besar Tunggakan","Status"};
            table_list2=new DefaultTableModel(null,rows);
            table_list_student2.setModel(table_list2);
            table_list_student2.setBorder(null);
            jScrollPane1.setVisible(true);
            jScrollPane1.setViewportView(table_list_student2);
            table_list_student2.setVisible(true);
            if (table_list_student.getRowCount() > 0) {
                if (table_list_student.getSelectedRowCount() > 0) {
                int[] selectedRow = table_list_student.getSelectedRows();
                    for (int i : selectedRow) {
                        List<String> bulan = get_month();
                        for (String subjek : bulan) {                            
                            String debt_code        = random_string(8).toUpperCase();
                            String debt_subject     = subjek;
                            String student_id       = table_list_student.getValueAt(i,0).toString();
                            String student_fullname = table_list_student.getValueAt(i,1).toString();
                            String[] tampil = {debt_code, debt_subject, student_id, student_fullname, param3x,"Belum Lunas"};
                            table_list2.addRow(tampil);
                        }
                    }
                }
            }
            param1.setEnabled(false);
            param2.setEnabled(false);
            param3.setEnabled(false);
            save.setEnabled(true);
            process.setEnabled(false);
            table_list_student2.setEnabled(false);
            Component[] sm1 = semester1.getComponents();
            for(int i = 0; i < sm1.length; i++) sm1[i].setEnabled(false);
            Component[] sm2 = semester2.getComponents();
            for(int i = 0; i < sm2.length; i++) sm2[i].setEnabled(false);
            
        }else{
            JOptionPane.showMessageDialog(rootPane,error_msg,"Error",JOptionPane.ERROR_MESSAGE);
        }
         
        
    }//GEN-LAST:event_processActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            // TODO add your handling code here:
            Statement stmt = dbconnect.createStatement();
            
            String years        = (String) param1.getSelectedItem();
            String class_name   = (String) param2.getSelectedItem();

            Vector data_list = table_list2.getDataVector();
            
            int i;
            for ( i = 0; i < data_list.size(); i++) {
                List<String> data = (List<String>) data_list.get(i);
                        // [QYRCJZH1, Desember 2012, 15167041, NASYWAH SABINA BELVA, 900, Belum Lunas]

                sql = "INSERT INTO m_debt (debt_code, debt_description, years, student_id, class_name, debt_amount, debt_status)"
                    + "VALUES ('"+data.get(0)+"','"+data.get(1)+"','"+years+"','"+data.get(2)+"','"+class_name+"','"+data.get(4)+"','"+data.get(5)+"') ";
                stmt.executeUpdate(sql);
            }
            JOptionPane.showMessageDialog(rootPane,"Total "+i+" Data Tunggakan berhasil disimpan!","Berhasil",JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(debt_add_form.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane,"Error : "+ex,"Error",JOptionPane.ERROR);
        }       
    }//GEN-LAST:event_saveActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void param2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_param2ActionPerformed
        // TODO add your handling code here:
        where   = (String) param2.getSelectedItem();
        show_student_list(where);
    }//GEN-LAST:event_param2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sample_add_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sample_add_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sample_add_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sample_add_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sample_add_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bulan1;
    private javax.swing.JCheckBox bulan10;
    private javax.swing.JCheckBox bulan11;
    private javax.swing.JCheckBox bulan12;
    private javax.swing.JCheckBox bulan2;
    private javax.swing.JCheckBox bulan3;
    private javax.swing.JCheckBox bulan4;
    private javax.swing.JCheckBox bulan5;
    private javax.swing.JCheckBox bulan6;
    private javax.swing.JCheckBox bulan7;
    private javax.swing.JCheckBox bulan8;
    private javax.swing.JCheckBox bulan9;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_akademis;
    private javax.swing.JPanel panel_tunggakan;
    private javax.swing.JComboBox param1;
    private javax.swing.JComboBox param2;
    private javax.swing.JTextField param3;
    private javax.swing.JButton process;
    private javax.swing.JButton save;
    private javax.swing.JPanel semester1;
    private javax.swing.JPanel semester2;
    private javax.swing.JTable table_list_student;
    // End of variables declaration//GEN-END:variables

    private void sample_update() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void sample_save() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void clear_text() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private List<String> get_month(){
        String years   = (String) param1.getSelectedItem();
        
        List<String> bulan = new ArrayList<String>();      
        if(bulan7.isSelected()) bulan.add("Juli "       +years.substring(0,4));
        if(bulan8.isSelected()) bulan.add("Agustus "    +years.substring(0,4));
        if(bulan9.isSelected()) bulan.add("September "  +years.substring(0,4));
        if(bulan10.isSelected()) bulan.add("Oktober "   +years.substring(0,4));
        if(bulan11.isSelected()) bulan.add("November "  +years.substring(0,4));        
        if(bulan12.isSelected()) bulan.add("Desember "  +years.substring(0,4));  
        if(bulan1.isSelected()) bulan.add("Januari "    +years.substring(5));
        if(bulan2.isSelected()) bulan.add("Februari "   +years.substring(5));
        if(bulan3.isSelected()) bulan.add("Maret "      +years.substring(5));
        if(bulan4.isSelected()) bulan.add("April "      +years.substring(5));
        if(bulan5.isSelected()) bulan.add("Mei "        +years.substring(5));
        if(bulan6.isSelected()) bulan.add("Juni "       +years.substring(5));
        
        return bulan;
    }
    private String random_string(int len){

           StringBuilder sb = new StringBuilder( len );
           for( int i = 0; i < len; i++ ) 
              sb.append( AB.charAt( rnd.nextInt(AB.length()) ) );
           return sb.toString();
        
    }
     private void show_student_list(String str_where) {
       
        Object [] rows={"NIS","Nama Lengkap ","Kelas","Tempat Lahir","Tanggal Lahir","Jenis Kelamin","Alamat","Status"};
            table_list=new DefaultTableModel(null,rows);
            table_list_student.setModel(table_list);
            table_list_student.setBorder(null);
            jScrollPane1.setVisible(true);
            jScrollPane1.setViewportView(table_list_student);
            String student_id="",student_fullname="",class_name="",student_bplace="",student_bday="",student_sex="",student_address="",student_status="";
            try{
                
                //String sql="select * from m_student";
                 if(!str_where.equals("")){
                     sql  = "SELECT * FROM m_student WHERE student_status IN ('Aktif','Lulus') AND class_name = "+str_where;
                 }
                 
                Statement st = dbconnect.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    student_id          = rs.getString("student_id");
                    student_fullname    = rs.getString("student_fullname");
                    class_name          = rs.getString("class_name");
                    student_bplace      = rs.getString("student_bplace");
                    student_bday        = rs.getString("student_bday");
                    student_sex         = rs.getString("student_sex");
                    student_address     = rs.getString("student_address");
                    student_status      = rs.getString("student_status");

                    String [] tampil={student_id,student_fullname,class_name,student_bplace,student_bday,student_sex,student_address,student_status};
                    table_list.addRow(tampil);
                }
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Terdapat kesalahan query : "+e);
            }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
}
