/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package smpis_sistem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vandens
 */
public class student_list_form extends javax.swing.JInternalFrame {

    public Connection dbconnect = dbconnection.getConnection();
    public DefaultTableModel table_list;
    public String sql;
    private String where = "";
    public String key;
    /**
     * Creates new form student_list_form
     */
    public student_list_form() {
        initComponents();
        show_list(where);
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        param1 = new javax.swing.JTextField();
        param2 = new javax.swing.JTextField();
        param3 = new javax.swing.JTextField();
        param4 = new javax.swing.JCheckBox();
        param5 = new javax.swing.JCheckBox();
        param6 = new javax.swing.JComboBox();
        filter = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_list_student = new javax.swing.JTable();
        add_new = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setClosable(true);
        setTitle("Master Data Siswa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Filter Data Siswa"));

        jLabel1.setText("NIS");

        jLabel2.setText("Nama Siswa");

        jLabel3.setText("Kelas");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Status");

        param4.setText("Laki - Laki");

        param5.setText("Perempuan");

        param6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih satu", "Suspen", "Aktif", "Dihapus", "Lulus" }));
        param6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                param6ActionPerformed(evt);
            }
        });

        filter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/filter_add.png"))); // NOI18N
        filter.setText("Filter");
        filter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/filter_delete.png"))); // NOI18N
        clear.setText("Clear");
        clear.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(365, Short.MAX_VALUE)
                .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(59, 59, 59))))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(param4)
                        .addGap(18, 18, 18)
                        .addComponent(param5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(param2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(param1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(param3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(param6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(param1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(param2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(param3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(param4)
                    .addComponent(param5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(param6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filter)
                    .addComponent(clear)))
        );

        table_list_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIS", "Nama Lengkap Siswa", "Kelas", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "Alamat", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_list_student);
        if (table_list_student.getColumnModel().getColumnCount() > 0) {
            table_list_student.getColumnModel().getColumn(2).setMinWidth(50);
        }

        add_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/pencil_add.png"))); // NOI18N
        add_new.setText("Tambah");
        add_new.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_newActionPerformed(evt);
            }
        });

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/pencil_go.png"))); // NOI18N
        edit.setText("Edit");
        edit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16/pencil_delete.png"))); // NOI18N
        delete.setText("Hapus");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                        .addComponent(add_new)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add_new)
                        .addComponent(edit)
                        .addComponent(delete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void param6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_param6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_param6ActionPerformed

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        // TODO add your handling code here:

        String id                   = param1.getText();
        String name                 = param2.getText();
        String clas                 = param3.getText();
        String sex_l                = param4.getText();
        String sex_p                = param5.getText();
        String status               = (String) param6.getSelectedItem();

        boolean L_isSelected = param4.isSelected();
        boolean P_isSelected = param5.isSelected();

        where = "WHERE 1=1 ";
        if(!id.equals(""))                                      where = where+" AND student_id          = '"+id+"'";
        if(!name.equals(""))                                    where = where+" AND student_fullname    LIKE '%"+name+"%'";
        if(!clas.equals(""))                                    where = where+" AND class_name          = '"+clas+"'";
        if(L_isSelected && !P_isSelected)                       where = where+" AND student_sex         = 'L'";
        if(P_isSelected && !L_isSelected)                       where = where+" AND student_sex         = 'P'";
        if(!status.equals("") && !status.equals("Pilih satu"))  where = where+" AND student_status      = '"+status+"'";

        show_list(where);

    }//GEN-LAST:event_filterActionPerformed

    private void add_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_newActionPerformed
        // TODO add your handling code here:
        String flag = "Add";   
        student_add_form form = new student_add_form(flag);
        form.setLocationRelativeTo(null);
        form.setVisible(true); 
    }//GEN-LAST:event_add_newActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try{
            key = (String) table_list_student.getValueAt(table_list_student.getSelectedRow(),0);
            student_add_form form = new student_add_form(key);
            form.setLocationRelativeTo(null);
            form.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Tidak ada baris terseleksi ");
        }
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{

            key = (String) table_list_student.getValueAt(table_list_student.getSelectedRow(),0);
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Semua data tunggakan dan transaksi akan ikut terhapus.\n Anda yakin ingin melanjutkan?", "Konfirmasi", dialogButton);
            if(dialogResult == 0) {
                try {
                    if(1!=1){
                        // tambahkan validasi lainnya disini
                        JOptionPane.showMessageDialog(null,"Add Validation Here");
                    }else{

                        Statement stmt = dbconnect.createStatement();
                        // tidak benar-benar dihapus, hanya status saja
                        sql             = "UPDATE m_student SET student_status = 'Dihapus' WHERE student_id = '"+key+"'";
                        String sql2     = "UPDATE m_debt SET debt_status = 'Dihapus' WHERE student_id = '"+key+"'";
                        String sql3     = "UPDATE t_payment SET payment_status = 'Dihapus' WHERE student_id = '"+key+"'";
                        stmt.executeUpdate(sql);
                        stmt.executeUpdate(sql2);
                        stmt.executeUpdate(sql3);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(student_list_form.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                System.out.println("No Option");
            }
            show_list(where);

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Tidak ada baris terseleksi ");
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        param1.setText("");
        param2.setText("");
        param3.setText("");
        param4.setSelected(false);
        param5.setSelected(false);
        param6.setSelectedItem("Pilih satu");
         where = "WHERE 1=1 ";
        show_list(where);
    }//GEN-LAST:event_clearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_new;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton filter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField param1;
    private javax.swing.JTextField param2;
    private javax.swing.JTextField param3;
    private javax.swing.JCheckBox param4;
    private javax.swing.JCheckBox param5;
    private javax.swing.JComboBox param6;
    private javax.swing.JTable table_list_student;
    // End of variables declaration//GEN-END:variables

    private void show_list(String str_where) {
       
        Object [] rows={"NIS","Nama Lengkap ","Kelas","Tempat Lahir","Tanggal Lahir","Jenis Kelamin","Alamat","Status"};
            table_list=new DefaultTableModel(null,rows);
            table_list_student.setModel(table_list);
            table_list_student.setBorder(null);
            jScrollPane1.setVisible(true);
            jScrollPane1.setViewportView(table_list_student);
            String student_id="",student_fullname="",class_name="",student_bplace="",student_bday="",student_sex="",student_address="",student_status="";
            try{
                
                //String sql="select * from m_student";
                 if(!str_where.equals("")){
                     sql  = "SELECT * FROM m_student "+str_where;
                 }else{
                     sql  = "SELECT * FROM m_student";
                 }
                 
                Statement st = dbconnect.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    student_id          = rs.getString("student_id");
                    student_fullname    = rs.getString("student_fullname");
                    class_name          = rs.getString("class_name");
                    student_bplace      = rs.getString("student_bplace");
                    student_bday        = rs.getString("student_bday");
                    student_sex         = rs.getString("student_sex");
                    student_address     = rs.getString("student_address");
                    student_status      = rs.getString("student_status");

                    String [] tampil={student_id,student_fullname,class_name,student_bplace,student_bday,student_sex,student_address,student_status};
                    table_list.addRow(tampil);
                }
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Terdapat kesalahan query : "+e);
            }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
